[package]
name = "aoc"
version = "0.1.0"
authors = ["kipper"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
ego-tree = "0.6.2"